name: Stryker Pipeline

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x    
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore Calculator/Calculator.sln
    - name: Build
      run: dotnet build Calculator/Calculator.sln --no-restore
    - name: Unit Test
      run: dotnet test - name: Test
  run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal Calculator/Calculator.sln
    - name: Copy Coverage to root
      run: cp Calculator/Calculator.Tests/TestResults/**/coverage.opencover.xml coverage.opencover.xml
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage.opencover.xml
        fail_below_min: true
        format: markdown
        output: both
        thresholds: '80'
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: coverage.opencover.xml
        gist-filename: code-coverage.json
        gist-id: 9ad2229158bd5f447dc0ad93c42ae34f
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}       
    - name: Mutation Test
      run: dotnet stryker
    - name: Upload Mutation Report
      uses: actions/upload-artifact@v3.0.0
      with:
        name: mutation-report
        path: StrykerOutput
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2.2.0
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Glob match
      uses: tj-actions/glob@v10
      id: glob
      with: 
        files: StrykerOutput/**/reports/mutation-report.html
  
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2.2.0
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: steps.glob.outputs.paths[0]

